### ISSUE TITLE
range of longitude

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift-examples#16]
The ragged array files generated for the GDP datasets currently contain the `lon` variable with values in the interval ]-180,180] but the individual NetCDF generated by the DAC contain also the variable `lon360` which is the longitude between 0 and 360. Should we add this variable to the ragged array files? I'd say yes since space is not an issue and it makes life easier for the user.

**Comment by philippemiron** [comment]
I actually remove this variable during the processing of both the hourly and six-hourly dataset. I could put it back if needed.

https://github.com/Cloud-Drift/clouddrift-examples/blob/6334536993c799bf9fc5b7c21959169373f6114b/data/gdp.py#L472

**Comment by selipot** [comment]
Let's. I personally prefer my longitudes between 0 and 360.

**Comment by selipot** [comment]
Let's add back the lon360 variable to the ragged arrays.

**Comment by selipot** [comment]
Should the `lon360` new variable be a `data` variable or a `coords` variable in the ragged array? Perhaps simply a `data` variable in order to not duplicate the coordinates? @philippemiron what do you think?

**Comment by philippemiron** [comment]
I think as an extra `data` field, it would be fine. The main difference is that you can perform some operations with the coordinates in xarray (it has no effect in Awkward Array). Since we already have one longitude, it won't add much to also have `lon360` as a coordinate.

**Comment by selipot** [comment]
ok, let's make it a coordinate as well then!

**Comment by selipot** [comment]
I have tried to add `lon360` as a coordinate for the `gdp.ipynb` notebook but I have not been successful. The `RaggedArray.from_files` method takes as an argument a dictionary of coordinates but the `gdp.preprocess` function in `gdp.py` also seems to set the coordinates so I think that may be why?

**Comment by philippemiron** [comment]
You are right. I think what is assumed is that a variable has to be a coordinate (when returned by `preprocess`) to be added to the coordinates list.

I was hoping to fix #15 before modifying this to avoid conflict since it requires modifying the same files. I think it should work by setting `lon360` inside the `preprocess` as coordinates with `xr.set_coords` ([link](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.set_coords.html)), and then simply adding `lon360` to `RaggedArray.from_files` dictionary.

**Comment by selipot** [comment]
fixed with #17

**Comment by selipot** [comment]
fixed with #17
